using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace BullsAndCows
{
    /// <summary>
    /// Determine the logic and methods controlling the game flow.
    /// </summary>
    public class Engine
    {
        /// <summary>
        /// Symbol used to hide the unrevealed digits of the secret number.
        /// </summary>
        private const char HIDING_SYMBOL = 'X';

        /// <summary>
        /// Number representing the count of moves that are cheats.
        /// </summary>
        private int numberOfCheats;

        /// <summary>
        /// Number representing the count of moves that player has done(not including cheat moves).
        /// </summary>
        private int numberOfMoves;

        /// <summary>
        /// Random number generated by <see cref="GenerateNumberForGuess()"/> as a string.
        /// </summary>
        private string numberToGuess;

        /// <summary>
        /// Keeps true or false value depending from the game current state or more specific is the secret number is already guessed.
        /// </summary>
        private bool isGuessed;

        /// <summary>
        /// Container for hiding  partially the secret number from the user when use 'help' command, depending of how many times is used the command.
        /// </summary>
        private char[] helpingNumber;

        /// <summary>
        /// Initializes a new instance of the <see cref="Engine"/> class.
        /// </summary>
        public Engine()
        {
        }

        /// <summary>
        /// Entry point of the Engine. All High - level game logic methods are invoked in this methods to begin the game.
        /// </summary>
        public void Play()
        {
            CommandParser consoleReader = new CommandParser();
            UserInterface.PrintGameRulesMessage();
            this.Initialize();

            string command = null;

            while (!this.isGuessed)
            {
                Console.Write("Enter your guess or command: ");
                command = Console.ReadLine();
                command = consoleReader.ParseCommand(command);
                this.CommandExecution(command);
            }
            //if(this.numberOfCheats>0)
            //string nickName = HallOfFame.ValidateNickName();
            HallOfFame.AddPlayerToScoreboard(this.numberOfMoves, this.numberOfCheats);

            string scoreBoard = HallOfFame.GenerateScoreBoard();
            Console.WriteLine(scoreBoard);

            this.CreateNewGame();
        }

        /// <summary>
        /// Initialize <see cref="Engine"/> class fields to their default values need for the normal execution of the game.
        /// </summary>
        private void Initialize()
        {
            this.GenerateNumberForGuess();
            this.helpingNumber = new char[this.numberToGuess.Length];
            this.numberOfMoves = 0;
            this.numberOfCheats = 0;
            this.isGuessed = false;

            for (int helpingNumberIndex = 0; helpingNumberIndex < this.helpingNumber.Length; helpingNumberIndex++)
            {
                this.helpingNumber[helpingNumberIndex] = Engine.HIDING_SYMBOL;
            }
        }

        /// <summary>
        /// Generate a secret number for the user to guess in the range of 1000 - 9999.
        /// </summary>
        private void GenerateNumberForGuess()
        {
            Random randomSecretNumberGenerator = new Random();

            this.numberToGuess = randomSecretNumberGenerator.Next(1000, 9999).ToString();
        }

        /// <summary>
        /// Decides did the guess is the secret number otherwise notify the user for number of 'cows' and 'bulls'.
        /// </summary>
        /// <param name="numberToTry">Number representing try of the user to guess the secret number.</param>
        private void ProcessNextMove(string numberToTry)
        {
            this.numberOfMoves++;
            if (this.IsEqualToNumberForGuess(numberToTry))
            {
                this.isGuessed = true;
                UserInterface.PrintCongratulationMessage(this.numberOfMoves, this.numberOfCheats);
            }
            else
            {
                Cow cow = new Cow(this.numberToGuess, numberToTry);
                Bull bull = new Bull(this.numberToGuess, numberToTry);

                Console.WriteLine("Wrong number! ");
                bull.DrawToConsole();
                cow.DrawToConsole();
            }
        }

        /// <summary>
        /// Execute game command or notify the user for invalid one.
        /// </summary>
        /// <param name="command">Name of the command to be executed.</param>
        private void CommandExecution(string command)
        {
            switch (command.ToLower())
            {
                case "top":
                    string scoreBoard = HallOfFame.GenerateScoreBoard();
                    Console.WriteLine(scoreBoard);
                    break;
                case "help":
                    this.RevealDigit();
                    break;
                case "restart":
                    this.CreateNewGame();
                    return;
                case "exit":
                    Console.WriteLine("Good bye!");
                    Environment.Exit(1);
                    break;
                case "invalid command":
                    Console.WriteLine("Invalid command!");
                    break;
                case "invalid number":
                    Console.WriteLine("You have entered invalid number!");
                    break;
                default:
                    this.ProcessNextMove(command);
                    break;
            }
        }

        /// <summary>
        /// Creates new game for the same instance of the Engine.
        /// </summary>
        private void CreateNewGame()
        {
            this.Play();
        }

        /// <summary>
        /// Check is the user guess is right.
        /// </summary>
        /// <param name="numberToTry">Number representing try of the user to guess the secret number</param>
        /// <returns>True for right guess and false for opposite.</returns>
        private bool IsEqualToNumberForGuess(string numberToTry)
        {
            bool isEqualToNumberForGuess = (numberToTry == this.numberToGuess);

            return isEqualToNumberForGuess;
        }

        /// <summary>
        /// Reveals one digit from the secret number each time is invoked and print it on the Console.
        ///     Never reveals already revealed digit.
        /// </summary>
        private void RevealDigit()
        {
            bool flag = true;

            while (flag)
            {
                Random randomIndexGenerator = new Random();
                int digitForReveal = randomIndexGenerator.Next(0, 4);

                if (this.helpingNumber[digitForReveal] == Engine.HIDING_SYMBOL)
                {
                    this.helpingNumber[digitForReveal] = this.numberToGuess[digitForReveal];
                    flag = false;
                }
            }

            this.numberOfCheats++;
            this.PrintHelpingNumber();
        }

        /// <summary>
        /// Used in the <see cref="PrintHelpingNumber()"/> to print on the Console all numbers revealed by the command 'help'. 
        /// </summary>
        private void PrintHelpingNumber()
        {
            Console.Write("The number looks like ");
            foreach (char ch in this.helpingNumber)
            {
                Console.Write(ch);
            }

            Console.Write(".");
            Console.WriteLine();
        }
    }
}
